backend = "glx";

blur-background = true;
blur-method = "gaussian";
blur-strenght = 5;

vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

opacity-rule = [
    "90:class_g = 'konsole'"
];

